language: python
sudo: true
python:
  - "3.5"
  - "3.6"
only:
  - master
  
addons:
 firefox: "latest"

env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
install:   
  - pip install -I Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  
before_script:
script:
  - PYTHONWARNINGS=all pytets --cov=.
  - py.test calculator/main_test.py
  
aftere_success:
  - codecov
  
